balancing_robot:
  #Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  gazebo_ros_control:
    pid_gains:
      right_wheel_joint:         {p: 100.0, i: 16, d: 20}
      left_wheel_joint:          {p: 100.0, i: 16, d: 20}


  left_wheel:
    type: effort_controllers/JointEffortController
    joint: left_wheel_joint

  right_wheel:
    type: effort_controllers/JointEffortController
    joint: right_wheel_joint
    
# position_controllers/JointPositionController
# effort_controllers/JointEffortController
# velocity_controllers/JointVelocityController