quadruped_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  
  # gazebo_ros_control:
  #   pid_gains:
  #     LM : {p: 35000, d: 800}


  # Driving Parts
  # effort_controllers / position_controllers
  # JointEffortController / JointPositionController
  # LM_pos:
  #   type: position_controllers/JointPositionController
  #   joint: LM
    # pid: {p: 30.0, i: 0.01, d: 15}
  RW_pos:
    type: effort_controllers/JointEffortController
    joint: RW
    pid: {p: 30.0, i: 0.01, d: 15}
  LW_pos:
    type: effort_controllers/JointEffortController
    joint: LW
    pid: {p: 30.0, i: 0.01, d: 15}
#velocity_controllers/JointVelocityController